# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba2f464aaa964e23da340b1d9f6e74552167e59e08c87800680f89013ceb6684db227ee751bdaf0bf926a449be31d7c472df69ce6c799b794abc147a78c6c53a

test:
  secret_key_base: 08dbce59eba447aa83afa4253a6c82a7d2212ca1b929634c541461f44da12a3bf0dfa1c97cce4a178e8ad465335d4888897f9729ccd52695874c33bd84fa91b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
